[package]
name = "elliptic-curve"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
modular_math = "0.1.6"
pkcs8 = { version = "0.10.2", features = ["pem"] }
primitive-types = { version = "0.12.2", features = ["num-traits"] }
rand = "0.8.5"
